from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]

PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

CLEAN_DATA_PATH = PROCESSED_DATA_DIR / "online_retail_clean.csv"
VALID_SALES_PATH = PROCESSED_DATA_DIR / "online_retail_valid_sales.csv"
CUSTOMER_SALES_PATH = PROCESSED_DATA_DIR / "online_retail_customer_sales.csv"


def load_processed_data() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Load processed datasets generated by the cleaning pipeline.
    """
    required_files = [
        CLEAN_DATA_PATH,
        VALID_SALES_PATH,
        CUSTOMER_SALES_PATH,
    ]

    missing_files = [path for path in required_files if not path.exists()]

    if missing_files:
        missing = "\n".join(str(path) for path in missing_files)
        raise FileNotFoundError(
            "Processed data files were not found. "
            "Run 'python src/clean_data.py' first.\n"
            f"Missing files:\n{missing}"
        )

    clean_data = pd.read_csv(CLEAN_DATA_PATH)
    valid_sales = pd.read_csv(VALID_SALES_PATH)
    customer_sales = pd.read_csv(CUSTOMER_SALES_PATH)

    return clean_data, valid_sales, customer_sales


def validate_valid_sales(valid_sales: pd.DataFrame) -> None:
    """
    Validate business rules for the valid sales dataset.
    """
    assert not valid_sales["InvoiceNo"].astype(str).str.startswith("C").any(), (
        "Valid sales contains cancellation invoices."
    )

    assert (valid_sales["Quantity"] > 0).all(), (
        "Valid sales contains Quantity <= 0."
    )

    assert (valid_sales["UnitPrice"] > 0).all(), (
        "Valid sales contains UnitPrice <= 0."
    )

    assert valid_sales["Description"].notna().all(), (
        "Valid sales contains missing Description."
    )

    assert valid_sales["InvoiceDate"].notna().all(), (
        "Valid sales contains missing InvoiceDate."
    )

    revenue_check = valid_sales["Quantity"] * valid_sales["UnitPrice"]

    assert revenue_check.round(2).equals(valid_sales["Revenue"].round(2)), (
        "Revenue calculation is inconsistent in valid sales."
    )


def validate_customer_sales(customer_sales: pd.DataFrame) -> None:
    """
    Validate business rules for the customer sales dataset.
    """
    assert customer_sales["CustomerID"].notna().all(), (
        "Customer sales contains missing CustomerID."
    )

    assert not customer_sales["InvoiceNo"].astype(str).str.startswith("C").any(), (
        "Customer sales contains cancellation invoices."
    )

    assert (customer_sales["Quantity"] > 0).all(), (
        "Customer sales contains Quantity <= 0."
    )

    assert (customer_sales["UnitPrice"] > 0).all(), (
        "Customer sales contains UnitPrice <= 0."
    )


def print_validation_summary(
    clean_data: pd.DataFrame,
    valid_sales: pd.DataFrame,
    customer_sales: pd.DataFrame,
) -> None:
    """
    Print validation summary and key coverage indicators.
    """
    valid_sales_revenue = valid_sales["Revenue"].sum()
    customer_sales_revenue = customer_sales["Revenue"].sum()

    missing_customer_revenue = valid_sales_revenue - customer_sales_revenue
    missing_customer_revenue_share = (
        missing_customer_revenue / valid_sales_revenue
    ) * 100

    missing_customer_rows = len(valid_sales) - len(customer_sales)
    missing_customer_rows_share = (missing_customer_rows / len(valid_sales)) * 100

    print("=" * 80)
    print("PROCESSED DATA VALIDATION SUMMARY")
    print("=" * 80)

    print("\n1. Dataset shapes")
    print(f"Clean data: {clean_data.shape[0]:,} rows, {clean_data.shape[1]:,} columns")
    print(f"Valid sales: {valid_sales.shape[0]:,} rows, {valid_sales.shape[1]:,} columns")
    print(
        f"Customer sales: {customer_sales.shape[0]:,} rows, "
        f"{customer_sales.shape[1]:,} columns"
    )

    print("\n2. Revenue coverage")
    print(f"Valid sales revenue: {valid_sales_revenue:,.2f}")
    print(f"Customer sales revenue: {customer_sales_revenue:,.2f}")
    print(f"Revenue without identified customer: {missing_customer_revenue:,.2f}")
    print(
        "Revenue without identified customer share: "
        f"{missing_customer_revenue_share:.2f}%"
    )

    print("\n3. Row coverage")
    print(f"Valid sales rows without identified customer: {missing_customer_rows:,}")
    print(
        "Valid sales rows without identified customer share: "
        f"{missing_customer_rows_share:.2f}%"
    )

    print("\nValidation result")
    print("All processed data validation checks passed.")


if __name__ == "__main__":
    clean_data, valid_sales, customer_sales = load_processed_data()

    validate_valid_sales(valid_sales)
    validate_customer_sales(customer_sales)

    print_validation_summary(clean_data, valid_sales, customer_sales)